feat: increase right padding
AlaskaAirlines/auro-alerts pull request #4
Opened 2020-10-05 22:30 UTC by geoffrich

# Alaska Airlines Pull Request

## Summary:

Per @sryckman, increase the right padding of the alert component to 1rem.

Before:
![image](https://user-images.githubusercontent.com/4992896/95138591-739d4780-071f-11eb-8a55-325c1fb7c399.png)

After:
![image](https://user-images.githubusercontent.com/4992896/95138652-97f92400-071f-11eb-8242-f3f8891a129c.png)

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2020-10-07 22:05 UTC, blackfalcon requested changes
This is not a `feat`, but a `fix`. Please update the commit type prior to release.

2020-10-08 14:39 UTC, geoffrich commented
Commit has been reworded.

2020-10-17 05:11 UTC, blackfalcon approved these changes

2020-10-17 05:11 UTC, merged

2020-10-17 05:13 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 1.1.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-alerts/v/1.1.1)
- [GitHub release](https://github.com/AlaskaAirlines/auro-alerts/releases/tag/v1.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: